apiVersion: v2
name: argocd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 6.7.2
    repository: https://argoproj.github.io/argo-helm
  - name: argo-workflows
    version: 0.40.14
    repository: https://argoproj.github.io/argo-helm