argocd:
  global:
    domain: argocd.duckdns.org

argo-workflows:
  workflow:
    serviceAccount:
      create: true
    rbac:
      create: true
  controller:
    rbac:
      create: true
  server:
    authMode: "server"