apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cactustech-challenge
  namespace: cactustech
spec:
  project: default
  source:
    repoURL: https://github.com/luisvillatoro/cactus-challenge.git
    targetRevision: HEAD
    path: charts
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true