replicaCount: 1
image:
  repository: 672262484140.dkr.ecr.us-east-1.amazonaws.com/cactustech-challenge

publicUrl: "cactus-stag-challengedevops.duckdns.org"

specs:
  ingress:
    publicUrl: challengedevops.duckdns.org
    port: 3000
  service:
    name: http
    port: 3000
    protocol: TCP
    type: ClusterIP

env:
  URL: "cactus-stag-challengedevops.duckdns.org:80"